version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: server-monitor-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=sqlite:///instance/portal.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-change-this-secret-key-in-production}
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    networks:
      - server-monitor-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: server-monitor-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - server-monitor-network

networks:
  server-monitor-network:
    driver: bridge

volumes:
  instance-data:

